export class Currency {
    constructor(
        public name: string,
        public code: string,
        public symbol: string) {
        
    }
}

export const CURRENCIES: Array<Currency> = [
    new Currency('Albania Lek', 'ALL', 'Lek'),
    new Currency('Afghanistan Afghani', 'AFN', '؋'),
    new Currency('Argentina Peso', 'ARS', '$'),
    new Currency('Aruba Guilder', 'AWG', 'ƒ'),
    new Currency('Australia Dollar', 'AUD', '$'),
    new Currency('Azerbaijan Manat', 'AZN', '₼'),
    new Currency('Bahamas Dollar', 'BSD', '$'),
    new Currency('Barbados Dollar', 'BBD', '$'),
    new Currency('Belarus Ruble', 'BYN', 'Br'),
    new Currency('Belize Dollar', 'BZD', 'BZ$'),
    new Currency('Bermuda Dollar', 'BMD', '$'),
    new Currency('Bolivia Bolíviano', 'BOB', '$b'),
    new Currency('Bosnia and Herzegovina Convertible Marka', 'BAM', 'KM'),
    new Currency('Botswana Pula', 'BWP', 'P'),
    new Currency('Bulgaria Lev', 'BGN', 'лв'),
    new Currency('Brazil Real', 'BRL', 'R$'),
    new Currency('Brunei Darussalam Dollar', 'BND', '$'),
    new Currency('Cambodia Riel', 'KHR', '៛'),
    new Currency('Canada Dollar', 'CAD', '$'),
    new Currency('Cayman Islands Dollar', 'KYD', '$'),
    new Currency('Chile Peso', 'CLP', '$'),
    new Currency('China Yuan Renminbi', 'CNY', '¥'),
    new Currency('Colombia Peso', 'COP', '$'),
    new Currency('Costa Rica Colon', 'CRC', '₡'),
    new Currency('Croatia Kuna', 'HRK', 'kn'),
    new Currency('Cuba Peso', 'CUP', '₱'),
    new Currency('Czech Republic Koruna', 'CZK', 'Kč'),
    new Currency('Denmark Krone', 'DKK', 'kr'),
    new Currency('Dominican Republic Peso', 'DOP', 'RD$'),
    new Currency('East Caribbean Dollar', 'XCD', '$'),
    new Currency('Egypt Pound', 'EGP', '£'),
    new Currency('El Salvador Colon', 'SVC', '$'),
    new Currency('Euro Member Countries', 'EUR', '€'),
    new Currency('Falkland Islands (Malvinas) Pound', 'FKP', '£'),
    new Currency('Fiji Dollar', 'FJD', '$'),
    new Currency('Ghana Cedi', 'GHS', '¢'),
    new Currency('Gibraltar Pound', 'GIP', '£'),
    new Currency('Guatemala Quetzal', 'GTQ', 'Q'),
    new Currency('Guernsey Pound', 'GGP', '£'),
    new Currency('Guyana Dollar', 'GYD', '$'),
    new Currency('Honduras Lempira', 'HNL', 'L'),
    new Currency('Hong Kong Dollar', 'HKD', '$'),
    new Currency('Hungary Forint', 'HUF', 'Ft'),
    new Currency('Iceland Krona', 'ISK', 'kr'),
    new Currency('India Rupee', 'INR', ''),
    new Currency('Indonesia Rupiah', 'IDR', 'Rp'),
    new Currency('Iran Rial', 'IRR', '﷼'),
    new Currency('Isle of Man Pound', 'IMP', '£'),
    new Currency('Israel Shekel', 'ILS', '₪'),
    new Currency('Jamaica Dollar', 'JMD', 'J$'),
    new Currency('Japan Yen', 'JPY', '¥'),
    new Currency('Jersey Pound', 'JEP', '£'),
    new Currency('Kazakhstan Tenge', 'KZT', 'лв'),
    new Currency('Korea (North) Won', 'KPW', '₩'),
    new Currency('Korea (South) Won', 'KRW', '₩'),
    new Currency('Kyrgyzstan Som', 'KGS', 'лв'),
    new Currency('Laos Kip', 'LAK', '₭'),
    new Currency('Lebanon Pound', 'LBP', '£'),
    new Currency('Liberia Dollar', 'LRD', '$'),
    new Currency('Macedonia Denar', 'MKD', 'ден'),
    new Currency('Malaysia Ringgit', 'MYR', 'RM'),
    new Currency('Mauritius Rupee', 'MUR', '₨'),
    new Currency('Mexico Peso', 'MXN', '$'),
    new Currency('Mongolia Tughrik', 'MNT', '₮'),
    new Currency('Mozambique Metical', 'MZN', 'MT'),
    new Currency('Namibia Dollar', 'NAD', '$'),
    new Currency('Nepal Rupee', 'NPR', '₨'),
    new Currency('Netherlands Antilles Guilder', 'ANG', 'ƒ'),
    new Currency('New Zealand Dollar', 'NZD', '$'),
    new Currency('Nicaragua Cordoba', 'NIO', 'C$'),
    new Currency('Nigeria Naira', 'NGN', '₦'),
    new Currency('Norway Krone', 'NOK', 'kr'),
    new Currency('Oman Rial', 'OMR', '﷼'),
    new Currency('Pakistan Rupee', 'PKR', '₨'),
    new Currency('Panama Balboa', 'PAB', 'B/.'),
    new Currency('Paraguay Guarani', 'PYG', 'Gs'),
    new Currency('Peru Sol', 'PEN', 'S/.'),
    new Currency('Philippines Piso', 'PHP', '₱'),
    new Currency('Poland Zloty', 'PLN', 'zł'),
    new Currency('Qatar Riyal', 'QAR', '﷼'),
    new Currency('Romania Leu', 'RON', 'lei'),
    new Currency('Russia Ruble', 'RUB', '₽'),
    new Currency('Saint Helena Pound', 'SHP', '£'),
    new Currency('Saudi Arabia Riyal', 'SAR', '﷼'),
    new Currency('Serbia Dinar', 'RSD', 'Дин.'),
    new Currency('Seychelles Rupee', 'SCR', '₨'),
    new Currency('Singapore Dollar', 'SGD', '$'),
    new Currency('Solomon Islands Dollar', 'SBD', '$'),
    new Currency('Somalia Shilling', 'SOS', 'S'),
    new Currency('South Africa Rand', 'ZAR', 'R'),
    new Currency('Sri Lanka Rupee', 'LKR', '₨'),
    new Currency('Sweden Krona', 'SEK', 'kr'),
    new Currency('Switzerland Franc', 'CHF', 'CHF'),
    new Currency('Suriname Dollar', 'SRD', '$'),
    new Currency('Syria Pound', 'SYP', '£'),
    new Currency('Taiwan New Dollar', 'TWD', 'NT$'),
    new Currency('Thailand Baht', 'THB', '฿'),
    new Currency('Trinidad and Tobago Dollar', 'TTD', 'TT$'),
    new Currency('Turkey Lira', 'TRY', ''),
    new Currency('Tuvalu Dollar', 'TVD', '$'),
    new Currency('Ukraine Hryvnia', 'UAH', '₴'),
    new Currency('United Kingdom Pound', 'GBP', '£'),
    new Currency('United States Dollar', 'USD', '$'),
    new Currency('Uruguay Peso', 'UYU', '$U'),
    new Currency('Uzbekistan Som', 'UZS', 'лв'),
    new Currency('Venezuela Bolívar', 'VEF', 'Bs'),
    new Currency('Viet Nam Dong', 'VND', '₫'),
    new Currency('Yemen Rial', 'YER', '﷼'),
    new Currency('Zimbabwe Dollar', 'ZWD', 'Z$')

]